//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""InGameInput"",
            ""id"": ""ef5fe6a9-c983-4aec-851b-5757bf0cddf9"",
            ""actions"": [
                {
                    ""name"": ""SummonUnit"",
                    ""type"": ""Button"",
                    ""id"": ""0148bb57-e489-4548-a73c-ff5fa1a6470b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CastSpell"",
                    ""type"": ""Button"",
                    ""id"": ""e68f3e3d-88c4-4f56-a419-247ffb943d53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cheat"",
                    ""type"": ""Button"",
                    ""id"": ""42cfba58-d317-4e82-b9d1-3e6872ca1933"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""0ef19aaf-bc3b-419b-8d1c-ccfc154f0b6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnitSelection"",
                    ""type"": ""Button"",
                    ""id"": ""64ac4348-c12a-4f79-86b6-9a5423bbb9aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SpellSelection"",
                    ""type"": ""Button"",
                    ""id"": ""862d9599-d22f-4664-9625-77b7fda79f73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GameSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""bfeafb3b-918f-4332-9c15-3db4431017ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""514380c9-3436-42ed-bff9-ac4ccc8bb3b5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SummonUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""532fbe81-4cae-4d8c-bd21-ce775eeb0102"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SummonUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b2b0cfb-a9c3-431d-be4c-817e76d0205e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SummonUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efded04b-28d9-40b8-80d3-90408e5e2f9a"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CastSpell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""062e39cd-35ba-41db-8f60-f317472146ea"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CastSpell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a314f9c2-70d5-4e4b-bcf3-9eaae00c65c7"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CastSpell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""809afc6b-5d42-44e2-a50b-21f5ba809f00"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Cheat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e6e762a-2303-4a25-9e58-7d9c5a3c590a"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cheat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06791b9e-a7a4-4f38-8410-668ca7a1c9d0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5687d4c-9b7d-47cc-9022-4542e9f19d33"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""c3777657-d15b-455e-af37-f08d9c731e4f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnitSelection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e495b2b0-874f-4781-ab82-e7c6e4dc0356"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UnitSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2b105451-108c-4d50-9c0a-050a9a793191"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UnitSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""276c4e7c-d6f4-4954-9c37-e2b444d9338c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnitSelection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1ed86b27-18b6-43d0-a366-09faabb0d0f6"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UnitSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""bede8ba7-64da-4e9b-893c-2a1e0ffb67ec"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UnitSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePadAlt"",
                    ""id"": ""43785179-2545-4e7e-99b1-cca8f819b7a7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnitSelection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""14d9b2ec-4673-4bd0-a0e2-5f447f513938"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UnitSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1103bcd0-d93a-4fb0-b369-083ce281af0b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UnitSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""b7d3c20e-1b3c-44ec-aa78-c1bc6fe8120c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpellSelection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""dd54ad9a-a3cc-4663-bc0e-5d55ed865c51"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SpellSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2edd2af9-6d00-4ead-aa98-eee19ac280ed"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SpellSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""e91fbe84-27ff-4dd1-b7cc-1bf7c9ae5536"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpellSelection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""30cfdacc-19ed-4299-a3b3-6673f762cea8"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SpellSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""efd5d483-3629-46aa-9326-2689309881f6"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SpellSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamepadAlt"",
                    ""id"": ""0cd6d404-b792-46a9-a5ac-81a9f7b7d63c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpellSelection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b1bf2641-6312-4c25-b4a0-ec4fa8e8c154"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SpellSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0afe72bd-8f50-4ba0-889c-4882da202b1d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SpellSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""99b1fae0-68f5-4483-9077-efe1533b16e3"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""GameSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad9f221f-3014-4ef9-a46c-76763610ccb5"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""GameSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // InGameInput
        m_InGameInput = asset.FindActionMap("InGameInput", throwIfNotFound: true);
        m_InGameInput_SummonUnit = m_InGameInput.FindAction("SummonUnit", throwIfNotFound: true);
        m_InGameInput_CastSpell = m_InGameInput.FindAction("CastSpell", throwIfNotFound: true);
        m_InGameInput_Cheat = m_InGameInput.FindAction("Cheat", throwIfNotFound: true);
        m_InGameInput_Pause = m_InGameInput.FindAction("Pause", throwIfNotFound: true);
        m_InGameInput_UnitSelection = m_InGameInput.FindAction("UnitSelection", throwIfNotFound: true);
        m_InGameInput_SpellSelection = m_InGameInput.FindAction("SpellSelection", throwIfNotFound: true);
        m_InGameInput_GameSpeed = m_InGameInput.FindAction("GameSpeed", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGameInput
    private readonly InputActionMap m_InGameInput;
    private IInGameInputActions m_InGameInputActionsCallbackInterface;
    private readonly InputAction m_InGameInput_SummonUnit;
    private readonly InputAction m_InGameInput_CastSpell;
    private readonly InputAction m_InGameInput_Cheat;
    private readonly InputAction m_InGameInput_Pause;
    private readonly InputAction m_InGameInput_UnitSelection;
    private readonly InputAction m_InGameInput_SpellSelection;
    private readonly InputAction m_InGameInput_GameSpeed;
    public struct InGameInputActions
    {
        private @GameInput m_Wrapper;
        public InGameInputActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @SummonUnit => m_Wrapper.m_InGameInput_SummonUnit;
        public InputAction @CastSpell => m_Wrapper.m_InGameInput_CastSpell;
        public InputAction @Cheat => m_Wrapper.m_InGameInput_Cheat;
        public InputAction @Pause => m_Wrapper.m_InGameInput_Pause;
        public InputAction @UnitSelection => m_Wrapper.m_InGameInput_UnitSelection;
        public InputAction @SpellSelection => m_Wrapper.m_InGameInput_SpellSelection;
        public InputAction @GameSpeed => m_Wrapper.m_InGameInput_GameSpeed;
        public InputActionMap Get() { return m_Wrapper.m_InGameInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameInputActions set) { return set.Get(); }
        public void SetCallbacks(IInGameInputActions instance)
        {
            if (m_Wrapper.m_InGameInputActionsCallbackInterface != null)
            {
                @SummonUnit.started -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnSummonUnit;
                @SummonUnit.performed -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnSummonUnit;
                @SummonUnit.canceled -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnSummonUnit;
                @CastSpell.started -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnCastSpell;
                @CastSpell.performed -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnCastSpell;
                @CastSpell.canceled -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnCastSpell;
                @Cheat.started -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnCheat;
                @Cheat.performed -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnCheat;
                @Cheat.canceled -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnCheat;
                @Pause.started -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnPause;
                @UnitSelection.started -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnUnitSelection;
                @UnitSelection.performed -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnUnitSelection;
                @UnitSelection.canceled -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnUnitSelection;
                @SpellSelection.started -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnSpellSelection;
                @SpellSelection.performed -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnSpellSelection;
                @SpellSelection.canceled -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnSpellSelection;
                @GameSpeed.started -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnGameSpeed;
                @GameSpeed.performed -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnGameSpeed;
                @GameSpeed.canceled -= m_Wrapper.m_InGameInputActionsCallbackInterface.OnGameSpeed;
            }
            m_Wrapper.m_InGameInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SummonUnit.started += instance.OnSummonUnit;
                @SummonUnit.performed += instance.OnSummonUnit;
                @SummonUnit.canceled += instance.OnSummonUnit;
                @CastSpell.started += instance.OnCastSpell;
                @CastSpell.performed += instance.OnCastSpell;
                @CastSpell.canceled += instance.OnCastSpell;
                @Cheat.started += instance.OnCheat;
                @Cheat.performed += instance.OnCheat;
                @Cheat.canceled += instance.OnCheat;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @UnitSelection.started += instance.OnUnitSelection;
                @UnitSelection.performed += instance.OnUnitSelection;
                @UnitSelection.canceled += instance.OnUnitSelection;
                @SpellSelection.started += instance.OnSpellSelection;
                @SpellSelection.performed += instance.OnSpellSelection;
                @SpellSelection.canceled += instance.OnSpellSelection;
                @GameSpeed.started += instance.OnGameSpeed;
                @GameSpeed.performed += instance.OnGameSpeed;
                @GameSpeed.canceled += instance.OnGameSpeed;
            }
        }
    }
    public InGameInputActions @InGameInput => new InGameInputActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IInGameInputActions
    {
        void OnSummonUnit(InputAction.CallbackContext context);
        void OnCastSpell(InputAction.CallbackContext context);
        void OnCheat(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnUnitSelection(InputAction.CallbackContext context);
        void OnSpellSelection(InputAction.CallbackContext context);
        void OnGameSpeed(InputAction.CallbackContext context);
    }
}
